// Tipos de mensajes definidos en el protocolo
#define MSG_REGISTER "register"
#define MSG_REGISTER_SUCCESS "register_success"
#define MSG_BROADCAST "broadcast"
#define MSG_PRIVATE "private"
#define MSG_LIST_USERS "list_users"
#define MSG_LIST_USERS_RESPONSE "list_users_response"
#define MSG_USER_INFO "user_info"
#define MSG_USER_INFO_RESPONSE "user_info_response"
#define MSG_CHANGE_STATUS "change_status"
#define MSG_STATUS_UPDATE "status_update"
#define MSG_DISCONNECT "disconnect"
#define MSG_USER_DISCONNECTED "user_disconnected"
#define MSG_ERROR "error"
